import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import BackgroundGradient from "@/components/BackgroundGradient";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Helmet } from "react-helmet-async";

const faqs = [
  {
    question: "How does CareerGuide AI figure out the best career for me?",
    answer: "CareerGuide AI uses a blend of your personality traits (based on the RIASEC model), your academic potential, and your professional interests. By analyzing these factors together, it synchronizes the most suitable career pathways for you within the Kenyan educational context."
  },
  {
    question: "Is this platform suitable for Junior Secondary students?",
    answer: "Yes! CareerGuide AI is designed to support students across the entire Competency-Based Curriculum (CBC) in Kenya, from Junior Secondary exploring broad pathways, to Senior Secondary students making final career and tertiary education choices."
  },
  {
    question: "Do schools need a constant internet connection to use this?",
    answer: "While an internet connection is required for the initial AI assessments and to sync data, CareerGuide AI is optimized for low-bandwidth environments. Students can take assessments and mentors can use the dashboard without needing high-speed internet."
  },
  {
    question: "How does it align with the Kenyan CBE system?",
    answer: "Our AI is explicitly trained on the Kenyan Competency-Based Education framework. It recommends career pathways by matching your strengths to the specific learning areas and subjects available in the CBE curriculum, ensuring realistic academic transitions."
  },
  {
    question: "How can parents get involved?",
    answer: "While currently focused on students and schools, the detailed PDF reports generated by the AI assessment are perfect tools for students to share with their parents. These reports provide clear, actionable steps for parents to support their child's career journey."
  },
  {
    question: "How much does CareerGuide AI cost?",
    answer: "We offer two flexible models. For Individual Students, unlocking a full professional diagnostic report costs just KES 50. For Schools, our institutional plan starts at KES 100 per student per term, which includes unlimited access to dashboards, mentor insights, and student assessments."
  },
  {
    question: "Do students need to pay individual subscription fees?",
    answer: "No, our primary model is institutional—schools pay an affordable flat fee so that every student can access the platform. However, guest users who take a 'Quick Assessment' only pay a small fee of KES 50 to unlock and download their full verified PDF roadmap."
  },
  {
    question: "What security measures protect student data?",
    answer: "We take data privacy very seriously. All student data is end-to-end encrypted and stored in secure Supabase localized servers. We strictly adhere to the Kenya Data Protection Act of 2019, ensuring that school records remain under the school's sovereign control."
  },
  {
    question: "Which AI models drive the career matching?",
    answer: "We utilize a custom fine-tuned ensemble of models, including GPT-4o and DeepSeek-V3, which have been specifically trained on regional Kenyan economic data, TVET opportunities, and the CBC learning area mappings for maximum local relevance."
  },
  {
    question: "Is there a mobile app?",
    answer: "CareerGuide AI is a Progressive Web App (PWA). While we don't require an Apple/Play Store download, the entire platform is optimized for mobile browser use, allowing students and mentors to access their dashboards on any smartphone with minimal data usage."
  },
  {
    question: "How do mentors use the insights?",
    answer: "Mentors receive a 'Student Insight' dashboard which aggregates the career matching trends for their full roster. This helps them identify which industries their students are naturally leaning toward, allowing them to organize precise industry field trips and immersion days."
  }
];

const FAQ = () => {
  return (
    <div className="min-h-screen text-foreground relative overflow-x-hidden pt-20">
      <Helmet>
        <title>FAQ | CareerGuide AI - Frequently Asked Questions</title>
        <meta name="description" content="Find answers to common questions about CareerGuide AI, CBC alignment, data security, pricing, and how we help Kenyan schools." />
        
        {/* FAQ Structured Data for Google/AI Rich Results */}
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": faqs.map(faq => ({
              "@type": "Question",
              "name": faq.question,
              "acceptedAnswer": {
                "@type": "Answer",
                "text": faq.answer
              }
            }))
          })}
        </script>
      </Helmet>
      <BackgroundGradient />
      <Navigation />
      
      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24 relative z-10">
        <div className="text-center mb-16">
          <h1 className="text-4xl md:text-5xl font-bold mb-6">
            Frequently Asked{" "}
            <span className="bg-gradient-text bg-clip-text text-transparent">
              Questions
            </span>
          </h1>
          <p className="text-lg text-foreground-muted max-w-2xl mx-auto">
            Everything you need to know about CareerGuide AI, how it works, and how it benefits students and schools in Kenya.
          </p>
        </div>

        <div className="bg-gradient-surface border border-card-border rounded-2xl p-6 sm:p-10 shadow-elevated">
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={"item-" + index} className="border-card-border">
                <AccordionTrigger className="text-left font-semibold text-lg hover:text-primary transition-colors">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-foreground-muted leading-relaxed pb-6">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default FAQ;
